### ISSUE TITLE
What Python environment are you using?

### ISSUE THREAD

**Issue by kyler-huang** [dvdwndrdl/order-aware-alignments#1]
What Python environment are you using? I tried versions 3.6 to 3.9, but I couldn't run the code 'python main.py compute-order-aware-alignments -p <file-path> -l Bpic12.xes -m Bpic12_90.pnml'. Moreover, the compiler reported basic syntax errors.

**Comment by dvdwndrdl** [comment]
Please use Python 3.11+ since some of the code constructs were newly introduced to Python in 3.10.

**Comment by kyler-huang** [comment]
I downloaded the XES format dataset "Bpic12.xes" from the BPI Challenge 2012 and used the inductive algorithm to mine it, generating a Petri net model called "Bpic12_90.pnml". 

I placed both files in the directory "'C:\Users\Administrator\Desktop\order-aware-alignments-main'". 

Then, I attempted to run the code "python main.py compute-order-aware-alignments -p 'C:\Users\Administrator\Desktop\order-aware-alignments-main' -l Bpic12.xes -m Bpic12_90.pnml" in both Python 3.10 and 3.11 environments, but the results were unsuccessful. 

Can you please help me identify the errors or possible issues in my steps?

The error message is:
`
PS C:\Users\Administrator\Desktop\order-aware-alignments-main> python main.py compute-order-aware-alignments -p 'C:\Users\Administrator\Desktop\order-aware-alignments-main\' -l Bpic12.xes -m Bpic12_90.pnml
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\order-aware-alignments-main\main.py", line 11, in <module>
    from util.tools import compute_order_aware_alignments_for_sync_product_net, ExecutionVariant
  File "C:\Users\Administrator\Desktop\order-aware-alignments-main\util\tools.py", line 7, in <module>
    from algo.classic import AStar, AStarBidirectional, Dijkstra, DijkstraBidirectional, SplitPoint, SplitPointBidirectional
  File "C:\Users\Administrator\Desktop\order-aware-alignments-main\algo\classic\__init__.py", line 1, in <module>
    from .a_star import *
  File "C:\Users\Administrator\Desktop\order-aware-alignments-main\algo\classic\a_star.py", line 12, in <module>
    from util.heuristic_utils import compute_exact_heuristic, vectorize_initial_final_cost, derive_heuristic, \
  File "C:\Users\Administrator\Desktop\order-aware-alignments-main\util\heuristic_utils.py", line 3, in <module>
    import cvxpy as cp
  File "D:\Anaconda3\envs\order-aware-alignments-main310\lib\site-packages\cvxpy\__init__.py", line 18, in <module>
    import cvxpy.interface.scipy_wrapper
  File "D:\Anaconda3\envs\order-aware-alignments-main310\lib\site-packages\cvxpy\interface\scipy_wrapper.py", line 37, in <module>
    method = getattr(spmatrix, method_name)
AttributeError: type object 'spmatrix' has no attribute '__div__'. Did you mean: '__dir__'?
`

**Comment by kyler-huang** [comment]
I ran the code `pip install --upgrade cvxpy` to upgrade the package _cvxpy_ to version 1.3.2, and it seems to have resolved the issue I encountered earlier.
